package controller;

import java.io.IOException;

import com.lowagie.text.Document;
import com.lowagie.text.Font;
import com.lowagie.text.FontFactory;
import com.lowagie.text.Paragraph;
import com.lowagie.text.pdf.PdfWriter;

import dao.NoteDAO;
import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import jakarta.servlet.http.HttpSession;
import model.Note;
import model.User;

@WebServlet("/ExportPDFServlet")
public class ExportPDFServlet extends HttpServlet {

    private static final long serialVersionUID = 1L;

    @Override
    protected void doGet(HttpServletRequest request,
            HttpServletResponse response)
            throws ServletException, IOException {

        HttpSession session=request.getSession();

        User user=(User)session.getAttribute("user");

        if(user==null){

            response.sendRedirect("login.jsp");

            return;

        }

        int id=Integer.parseInt(request.getParameter("id"));

        NoteDAO dao=new NoteDAO();

        Note note=dao.getNoteById(id);

        if(note==null){

            response.sendRedirect("NotesServlet");

            return;

        }

        if(note.getUserId()!=user.getId()){

            response.sendRedirect("NotesServlet");

            return;

        }

        response.setContentType("application/pdf");

        response.setHeader(
                "Content-Disposition",
                "attachment; filename=\""
                + note.getTitle().replaceAll("\\s+","_")
                + ".pdf\"");

        Document pdf=new Document();

        try{

            PdfWriter.getInstance(
                    pdf,
                    response.getOutputStream());

            pdf.open();
         // ================= TITLE =================

            Font titleFont = FontFactory.getFont(
                    FontFactory.HELVETICA_BOLD,
                    22);

            Paragraph title = new Paragraph(
                    note.getTitle(),
                    titleFont);

            title.setSpacingAfter(20);

            pdf.add(title);

            // ================= DETAILS =================

            Font heading = FontFactory.getFont(
                    FontFactory.HELVETICA_BOLD,
                    14);

            Font normal = FontFactory.getFont(
                    FontFactory.HELVETICA,
                    12);

            pdf.add(new Paragraph(
                    "Created At : " + note.getCreatedAt(),
                    normal));

            pdf.add(new Paragraph(
                    "Updated At : " + note.getUpdatedAt(),
                    normal));

            pdf.add(new Paragraph(" "));

            pdf.add(new Paragraph(
                    "Note Content",
                    heading));

            pdf.add(new Paragraph(" "));

            // ================= CONTENT =================

            Paragraph content = new Paragraph(
                    note.getContent(),
                    normal);

            content.setSpacingAfter(20);

            pdf.add(content);

            // ================= FOOTER =================

            pdf.add(new Paragraph(" "));

            Paragraph line = new Paragraph(
            		"----------------------------------------------------------");

            		line.setSpacingBefore(15);

            		line.setSpacingAfter(10);

            		pdf.add(line);

            pdf.add(new Paragraph(
                    "Generated by DOCHUB Notes",
                    FontFactory.getFont(
                            FontFactory.HELVETICA_OBLIQUE,
                            11)));

            pdf.add(new Paragraph(
                    "Thank you for using DOCHUB!",
                    FontFactory.getFont(
                            FontFactory.HELVETICA,
                            11)));

            pdf.close();

            }catch(Exception e){

                e.printStackTrace();

            }finally{

                if(pdf.isOpen()){

                    pdf.close();

                }

            }
    }
 }
    